//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OverlayExtensionConfig) DeepCopyInto(out *OverlayExtensionConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OverlayExtensionConfig.
func (in *OverlayExtensionConfig) DeepCopy() *OverlayExtensionConfig {
	if in == nil {
		return nil
	}
	out := new(OverlayExtensionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OverlayExtensionConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OverlayExtensionConfigList) DeepCopyInto(out *OverlayExtensionConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OverlayExtensionConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OverlayExtensionConfigList.
func (in *OverlayExtensionConfigList) DeepCopy() *OverlayExtensionConfigList {
	if in == nil {
		return nil
	}
	out := new(OverlayExtensionConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OverlayExtensionConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OverlayExtensionConfigSpec) DeepCopyInto(out *OverlayExtensionConfigSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OverlayExtensionConfigSpec.
func (in *OverlayExtensionConfigSpec) DeepCopy() *OverlayExtensionConfigSpec {
	if in == nil {
		return nil
	}
	out := new(OverlayExtensionConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OverlayExtensionConfigStatus) DeepCopyInto(out *OverlayExtensionConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OverlayExtensionConfigStatus.
func (in *OverlayExtensionConfigStatus) DeepCopy() *OverlayExtensionConfigStatus {
	if in == nil {
		return nil
	}
	out := new(OverlayExtensionConfigStatus)
	in.DeepCopyInto(out)
	return out
}
