pr: none
trigger: none

# Placeholder for when we want to enable automatic queuing of pipeline from LSG's pipeline.
# Fully functional to queue off of ACN PR Pipeline
# resources:
#   pipelines:
#   - pipeline: ACN-PR # Name of the pipeline resource.
#     source: \Custom\Networking\ContainerNetworking\Azure Container Networking PR # The name of the pipeline referenced by this pipeline resource.
#     trigger: true # Run CNI | LSG Integration pipeline when any run of LSG defined pipeline completes


stages:
  - stage: setup
    displayName: Setup
    jobs:
      - job: env
        displayName: Setup
        pool:
          name: "$(BUILD_POOL_NAME_DEFAULT)"
        steps:
          - script: |
              echo "Setting up environment"
              go version
              echo "##vso[task.setvariable variable=commitID;isOutput=true]$(echo $(make revision)-$(date "+%d%H%M"))"
              echo "##vso[task.setvariable variable=cnsVersion;isOutput=true]$(CNS_VERSION)"
              echo "##vso[task.setvariable variable=cniVersion;isOutput=true]$(CNI_VERSION)"
              echo "##vso[task.setvariable variable=ipamVersion;isOutput=true]$(IPAM_VERSION)"

              echo "------"
              echo Queued by $(Build.QueuedBy)
              echo "Runtime Variables passed"
              echo "KernelType : $(KernelType)"
              echo "KernelVersion : $(KernelVersion)"
              echo "ProposedRepoVersion : $(ProposedRepoVersion)"
              echo "------"
              echo "KernelType Check"
              Kernel=$(KernelType)
              if [ $Kernel = 'proposed-azure' ]; then
                echo "KernelType is $Kernel , change to linux-azure"
                Kernel=linux-azure
              fi
              if [ $Kernel = 'proposed-edge' ]; then
                echo "KernelType is $Kernel , change to linux-azure-edge"
                Kernel=linux-azure-edge
              fi
              echo "Final KernelType : $Kernel"
              echo "##vso[task.setvariable variable=kernelType;isOutput=true]$Kernel"
            name: "SetEnvVars"
            displayName: "Set Environment Variables"
            condition: always()

  - template: lsg-cni-intergration-template.yaml
    parameters:
      name: linux_overlay
      clusterType: overlay-byocni-up
      clusterName: "kup-over"
      nodeCount: 2
      vmSize: Standard_B2ms
      arch: amd64
      cni: cniv2

  - template: lsg-cni-intergration-template.yaml
    parameters:
      name: cilium_overlay
      clusterType: overlay-byocni-nokubeproxy-up
      clusterName: "kup-cilover"
      nodeCount: 2
      vmSize: Standard_B2ms
      arch: amd64
      cni: cilium

  - stage: delete_resources
    displayName: "Delete Resources"
    pool:
      name: "$(BUILD_POOL_NAME_DEFAULT)"
    condition: always()
    dependsOn:
      - linux_overlay
      - cilium_overlay
      - setup
    variables:
      commitID: $[ stagedependencies.setup.env.outputs['SetEnvVars.commitID'] ]
    jobs:
      - job: delete
        displayName: Delete Cluster
        pool:
          name: "$(BUILD_POOL_NAME_DEFAULT)"
        strategy:
          matrix:
            linux_overlay:
              name: linux_overlay
              clusterName: "kup-over"
            cilium_overlay:
              name: cilium_overlay
              clusterName: "kup-cilover"
        steps:
          - template: ../../templates/delete-cluster.yaml
            parameters:
              name: $(name)
              clusterName: $(clusterName)-$(commitID)
              region: $(LOCATION)
              sub: $(SUB_AZURE_NETWORK_AGENT_BUILD_VALIDATIONS)
              svcConn: $(BUILD_VALIDATIONS_SERVICE_CONNECTION)
